### ISSUE TITLE
`playlist_max_videos` setting is ignored

### ISSUE THREAD

**Issue by BrainStone** [natumbri/mopidy-youtube#29]
If I set the config value `playlist_max_videos` to something higher like `200` adding a playlist still only adds 50 titles.

**Comment by natumbri** [comment]
Thanks. I'll look into this. Can you please post the [youtube] section of your mopidy config.

I hope you are enjoying the plug-in.

**Comment by BrainStone** [comment]
My config looks like this:

```toml
[youtube]
enabled = true
youtube_api_key =
threads_max = 4
search_results = 30
playlist_max_videos = 200
api_enabled = false
```

`mopidyctl config` shows the same.
